# configs/config.yaml
defaults:
  - _self_
  - problem: tsp_aco
  - llm_client: groq # Hydra sẽ load configs/llm_clients/groq.yaml

  # Optional clients cho các operator
  - llm_client@llm_long_ref: null
  - llm_client@llm_short_ref: null
  - llm_client@llm_crossover: null
  - llm_client@llm_mutation: null

  # Logging / output
  - override hydra/output: local
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  job:
    name: ${problem.problem_name}-${problem.problem_type}
    chdir: True

algorithm: reevo  # khác "eoh", "ael" nếu muốn
max_fe: 100
pop_size: 10
init_pop_size: 30
mutation_rate: 0.5
timeout: 20
diversify_init_pop: True
